version: "3.5"
services:

    portainer:
        container_name: portainer
        image: portainer/portainer-ce:latest
        restart: always
        network_mode: host
        ports:
            - '9000:9000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${CONFIG_DIR}/portainer:/data'

    jellyfin:
        container_name: jellyfin
        image: jellyfin/jellyfin:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '8096:8096'
            - '8920:8920'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${CONFIG_DIR}/jellyfin:/config'
            - '${CACHE_DIR}/jellyfin:/cache'
            - '${SHOWS_DIR}:/data/tvshows'
            - '${MOVIES_DIR}:/data/movies'
            - '${MUSIC_DIR}:/data/music'
            - '/opt/vc/lib:/opt/vc/lib'

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '8989:8989'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${CONFIG_DIR}/sonarr:/config'
            - '${SHOWS_DIR}:/tv'
            - '${DOWNLOAD_DIR}:/downloads'

    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '7878:7878'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${CONFIG_DIR}/radarr:/config'
            - '${MOVIES_DIR}:/movies'
            - '${DOWNLOAD_DIR}:/downloads'
	
    lidarr:
        container_name: lidarr
        image: linuxserver/lidarr:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '8686:8686'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${CONFIG_DIR}/lidarr:/config'
            - '${MUSIC_DIR}:/music'
            - '${DOWNLOAD_DIR}:/downloads'

    bazarr:
        container_name: bazarr
        image: linuxserver/bazarr:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '6767:6767'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
            - UMASK_SET=022
        volumes:
            - '${CONFIG_DIR}/bazarr:/config'
            - '${SHOWS_DIR}:/tv'
            - '${MOVIES_DIR}:/movies'

    jackett:
        container_name: jackett
        image: linuxserver/jackett:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '9117:9117'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
            - AUTO_UPDATE=true
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '${CONFIG_DIR}/jackett:/config'
            - '${DOWNLOAD_DIR}/torrent-blackhole:/downloads'

    qbittorrent:
        container_name: qbittorrent
        image: linuxserver/qbittorrent:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '6881:6881'
            - '6881:6881/udp'
            - '8080:8080'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
            - 'WEBUI_PORT=8080'
        volumes:
            - '${CONFIG_DIR}/qbittorrent:/config'
            - '${DOWNLOAD_DIR}:/downloads'
    
    heimdall:
        container_name: heimdall
        image: linuxserver/heimdall:latest
        restart: always
        network_mode: host
        ports:
            - '80:80'
            - '443:443'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TIMEZONE}'
        volumes:
            - '${CONFIG_DIR}/heimdall:/config'
    
    netdata:
        container_name: netdata
        image: netdata/netdata:latest
        restart: unless-stopped
        network_mode: host
        ports:
            - '19999:19999'
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
        cap_add:
            - SYS_PTRACE
        security_opt:
            - 'apparmor:unconfined'
        volumes:
            - '/etc/passwd:/host/etc/passwd:ro'
            - '/etc/group:/host/etc/group:ro'
            - '/proc:/host/proc:ro'
            - '/sys:/host/sys:ro'
